name: "CI"
on: # rebuild any PRs and master branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test
        run: |
          make install
          make test-ci
