name: "CI"
on: # rebuild any PRs and master branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up environment
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Test
        run: npm i && npm run ci
